Repository Yeungnam-Nyang/Yeungnam-Nyang-BE2, pull requests merged in 2024-12, with the labels that each got.

#61 ✨feat : Post Update API
  src/main/java/com/example/YNN/controller/PostController.java
  src/main/java/com/example/YNN/model/CatMap.java
  src/main/java/com/example/YNN/model/Picture.java
  src/main/java/com/example/YNN/model/Post.java
  src/main/java/com/example/YNN/service/PostService.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/test.java
Labels: ✨기능구현

#65 🐛fix:친구 추가 에러핸들링
  src/main/java/com/example/YNN/config/SecurityConfig.java
  src/main/java/com/example/YNN/constants/ErrorCode.java
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/error/CustomException.java
  src/main/java/com/example/YNN/error/ErrorResponse.java
  src/main/java/com/example/YNN/error/GlobalExceptionHandler.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: 🐛버그, ♻️수정

#67 ✨feat:friend profiile info
  src/main/java/com/example/YNN/DTO/FriendProfileDTO.java
  src/main/java/com/example/YNN/repository/PostRepository.java
  src/main/java/com/example/YNN/service/FriendService.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: ✨기능구현

#69 ✨feat:컨트롤러 추가 구현
  src/main/java/com/example/YNN/controller/FriendController.java
Labels: ✨기능구현

#70 🔖컨트롤러 추가 후 버전 업데이트
  src/main/java/com/example/YNN/controller/FriendController.java
Labels: 🔖릴리즈

#74 ✨feat:Security HTTPS SSL 설정
  src/main/java/com/example/YNN/YnnApplication.java
  src/main/java/com/example/YNN/config/SecurityConfig.java
  src/main/resources/bootsecurity.p12
Labels: ✨기능구현

#75 🔖HTTPS SSL 설정 후 새로운 버전 릴리즈
  src/main/java/com/example/YNN/YnnApplication.java
  src/main/java/com/example/YNN/config/SecurityConfig.java
  src/main/resources/bootsecurity.p12
Labels: 🔖릴리즈

#89 88 fixfriend add bug
  .github/workflows/main.yml
  src/main/java/com/example/YNN/YnnApplication.java
  src/main/java/com/example/YNN/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 🐛버그

#90 Develop
  src/main/java/com/example/YNN/config/SecurityConfig.java
Labels: 🐛버그

#91 🐛fix:친구 추가 요청 로직 수정
  src/main/java/com/example/YNN/model/Friend.java
  src/main/java/com/example/YNN/repository/FriendRepository.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: 🐛버그

#92 🔖새로운 버전 릴리즈 : 친구추가 관련 로직 수정, HTTPS 설정
  src/main/java/com/example/YNN/model/Friend.java
  src/main/java/com/example/YNN/repository/FriendRepository.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: 🔖릴리즈

#94 🐛fix:게시물 스탑워치 시간 리턴
  src/main/java/com/example/YNN/service/PostServiceImpl.java
Labels: 🐛버그

#95 🔖새로운 버전 릴리즈 : 스탑워치 시간 리턴 수정
  src/main/java/com/example/YNN/service/PostServiceImpl.java
Labels: 🔖릴리즈

#97 🐛fix:scrap 없을 경우 빈 배열 리턴
  src/main/java/com/example/YNN/service/ScrapServiceImpl.java
Labels: 🐛버그

#98 🔖새로운 버전 릴리즈 : 스크랩이 Null일 때 빈 List 리턴
  src/main/java/com/example/YNN/service/ScrapServiceImpl.java
Labels: 🔖릴리즈

#101 🐛Fix : 친구 요청 목록 수정
  README.md
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/repository/FriendRepository.java
  src/main/java/com/example/YNN/service/FriendService.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: 🐛버그

#103 ♻️refact:Swagger API Docs 작성 및 Friend CustomException 처리 + 기본 프사 설정
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
Labels: 📕문서, ♻️수정

#105 📕docs:Swagger API Docs 작성
  src/main/java/com/example/YNN/controller/AuthenticationController.java
  src/main/java/com/example/YNN/controller/CommentController.java
  src/main/java/com/example/YNN/controller/FileUploadController.java
  src/main/java/com/example/YNN/controller/FindController.java
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/controller/LikeController.java
  src/main/java/com/example/YNN/controller/NyangMapController.java
  src/main/java/com/example/YNN/controller/PostController.java
  src/main/java/com/example/YNN/controller/ScrapController.java
  src/main/java/com/example/YNN/controller/SignUpController.java
  src/main/java/com/example/YNN/controller/UserController.java
Labels: 📕문서

#106 🔖새로운 버전 릴리즈 : 친구 목록 수정, Swagger API Docs 작성
  src/main/java/com/example/YNN/controller/AuthenticationController.java
  src/main/java/com/example/YNN/controller/CommentController.java
  src/main/java/com/example/YNN/controller/FileUploadController.java
  src/main/java/com/example/YNN/controller/FindController.java
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/controller/LikeController.java
  src/main/java/com/example/YNN/controller/NyangMapController.java
  src/main/java/com/example/YNN/controller/PostController.java
  src/main/java/com/example/YNN/controller/ScrapController.java
  src/main/java/com/example/YNN/controller/SignUpController.java
  src/main/java/com/example/YNN/controller/UserController.java
  src/main/java/com/example/YNN/repository/FriendRepository.java
  src/main/java/com/example/YNN/service/FriendService.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
Labels: 🔖릴리즈

#108 107 refactprofileimage show all
  src/main/java/com/example/YNN/DTO/CommentResponseDTO.java
  src/main/java/com/example/YNN/repository/CommentRepository.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
Labels: ♻️수정

#109 🔖새로운 버전 릴리즈 : 댓글 조회 시 유저의 프로필 사진 데이터 전달
  src/main/java/com/example/YNN/DTO/CommentResponseDTO.java
  src/main/java/com/example/YNN/repository/CommentRepository.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
Labels: 🔖릴리즈

#111 ♻️Refact : 최근 게시물, 인기 게시물, 게시물 상세 조회 시 프로필 사진을 불러오도록 리팩토링
  src/main/java/com/example/YNN/DTO/PostResponseDTO.java
  src/main/java/com/example/YNN/controller/PostController.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
Labels: ♻️수정

#113 🔖새로운 버전 릴리즈 : 게시물 불러올 때 프로필 사진 불러오는 기능 추가
  src/main/java/com/example/YNN/DTO/PostResponseDTO.java
  src/main/java/com/example/YNN/controller/PostController.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
Labels: 🔖릴리즈

#114 112 deployhttps ssl certificate
  src/main/java/com/example/YNN/YnnApplication.java
  src/main/resources/bootsecurity.p12
Labels: 🚀배포

#115 Deploy
  src/main/java/com/example/YNN/YnnApplication.java
  src/main/resources/bootsecurity.p12
Labels: 🚀배포

#118 116 refactget friend profile image
  src/main/java/com/example/YNN/DTO/FriendResponseDTO.java
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
  src/main/resources/application.properties
Labels: ♻️수정

#119 🔖새로운 버전 릴리즈 : 친구 목록 조회 시 프로필 사진 반환
  src/main/java/com/example/YNN/DTO/FriendResponseDTO.java
  src/main/java/com/example/YNN/controller/FriendController.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
  src/main/resources/application.properties
Labels: 🔖릴리즈

#122 121 fixfriend accepted list
  README.md
  src/main/java/com/example/YNN/repository/FriendRepository.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: 🐛버그

#123 Deploy
  src/main/java/com/example/YNN/repository/FriendRepository.java
  src/main/java/com/example/YNN/service/FriendServiceImpl.java
Labels: 🚀배포

#125 124 fixpost response dto edit
  build.gradle
  src/main/java/com/example/YNN/DTO/SignUpDTO.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
  src/test/java/com/example/YNN/model/UserTest.java
  src/test/resources/application-test.yml
Labels: 🐛버그

#130 🐛fix:https->http
  src/main/java/com/example/YNN/config/SecurityConfig.java
Labels: 🐛버그

#133 🔖릴리즈 : HTTPS 인증서 적용 및 DB 시간을 서울로 설정 후 적용
  src/main/resources/application.properties
Labels: 🔖릴리즈

#134 🐛fix:어노테이션 수정
  src/main/java/com/example/YNN/model/Comment.java
Labels: 🐛버그

#136 Comment CreatedAt 다시 수정
  src/main/java/com/example/YNN/model/Comment.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
Labels: ♻️수정

#137 Deploy
  src/main/java/com/example/YNN/model/Comment.java
  src/main/java/com/example/YNN/service/CommentServiceImpl.java
Labels: 🚀배포
