Repository Yeungnam-Nyang/Yeungnam-Nyang-BE2, pull requests merged in 2024-11, with the labels that each got.

#35 ✨feat 유저 프로필 사진 업데이트 및 정보 수정/조회 기능
  .gitignore
  src/main/java/com/example/YNN/DTO/ProfileUpdateDTO.java
  src/main/java/com/example/YNN/DTO/UserProfileDTO.java
  src/main/java/com/example/YNN/controller/UserController.java
  src/main/java/com/example/YNN/model/Profile.java
  src/main/java/com/example/YNN/model/Student.java
  src/main/java/com/example/YNN/model/User.java
  src/main/java/com/example/YNN/repository/ProfileRepository.java
  src/main/java/com/example/YNN/service/UserService.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/images/토벤머리.png
Labels: ✨기능구현

#38 ✨feat:S3 이미지 버킷
  build.gradle
  src/main/java/com/example/YNN/config/S3Config.java
  src/main/java/com/example/YNN/config/SecurityConfig.java
  src/main/java/com/example/YNN/controller/FileUploadController.java
  src/main/resources/application.properties
Labels: ✨기능구현

#41 ✨feat:S3버킷 이미지 업로드 구현(게시판, 프로필)
  .gitignore
  src/main/java/com/example/YNN/controller/FileUploadController.java
  src/main/java/com/example/YNN/controller/UserController.java
  src/main/java/com/example/YNN/model/Profile.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
  src/main/java/com/example/YNN/service/s3/S3Service.java
  src/main/java/com/example/YNN/service/s3/S3ServiceImpl.java
  src/main/resources/application.properties
Labels: ✨기능구현

#42 🔖release: v 1.0.0 배포
  .gitignore
  src/main/java/com/example/YNN/controller/FileUploadController.java
  src/main/java/com/example/YNN/controller/UserController.java
  src/main/java/com/example/YNN/model/Profile.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
  src/main/java/com/example/YNN/service/UserServiceImpl.java
  src/main/java/com/example/YNN/service/s3/S3Service.java
  src/main/java/com/example/YNN/service/s3/S3ServiceImpl.java
  src/main/resources/application.properties
Labels: 🔖릴리즈

#57 ✨feat:거리에 따른 주변 게시물 마크 띄우기
  build.gradle
  src/main/java/com/example/YNN/DTO/NyangMapPostDTO.java
  src/main/java/com/example/YNN/DTO/PostResponseDTO.java
  src/main/java/com/example/YNN/controller/NyangMapController.java
  src/main/java/com/example/YNN/controller/PostController.java
  src/main/java/com/example/YNN/model/Comment.java
  src/main/java/com/example/YNN/model/Post.java
  src/main/java/com/example/YNN/repository/CatMapRepository.java
  src/main/java/com/example/YNN/service/NyangMapService.java
  src/main/java/com/example/YNN/service/NyangMapServiceImpl.java
  src/main/java/com/example/YNN/service/PostService.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
  src/main/java/com/example/YNN/util/EmojiConverter.java
  src/main/java/com/example/YNN/util/LocationCalculation.java
  src/main/resources/application.properties
Labels: ✨기능구현

#58 🐛fix:게시물 Null처리
  src/main/java/com/example/YNN/DTO/PostResponseDTO.java
  src/main/java/com/example/YNN/service/PostServiceImpl.java
Labels: ♻️수정
